import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#1A401A',
  },
  scrollContent: {
    backgroundColor: '#F5F7F5',
    paddingBottom: 28,
  },
  headerArea: {
    backgroundColor: '#1A401A',
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 34,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 32,
  },
  subtitle: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 16,
    fontWeight: '500',
    marginTop: 8,
  },
  gridWrap: {
    paddingHorizontal: 16,
    marginTop: -16,
  },
  grid: {
    backgroundColor: '#FFFFFF',
    borderRadius: 26,
    paddingHorizontal: 14,
    paddingTop: 22,
    paddingBottom: 18,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 16,
    elevation: 4,
  },
  footerActionWrap: {
    paddingHorizontal: 16,
    marginTop: 6,
    marginBottom: 8,
  },
  actionButton: {
    minHeight: 50,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2BA14A',
    shadowColor: '#2BA14A',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 3,
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  avatarCard: {
    width: '48%',
    alignItems: 'center',
    paddingVertical: 10,
    marginBottom: 8,
  },
  avatarRing: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: '#F0F7F1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImageWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    overflow: 'hidden',
  },
  avatarInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    overflow: 'hidden',
  },
  avatarImage: {
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  avatarCrop: {
    width: 64,
    height: 64,
  },
  avatarFallback: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#E5ECE6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarName: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 18,
    color: '#18301A',
    fontWeight: '600',
    textAlign: 'center',
  },
  avatarRole: {
    marginTop: 3,
    fontSize: 11,
    lineHeight: 14,
    color: '#6B7B6E',
    fontWeight: '400',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 28, 13, 0.58)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    paddingHorizontal: 22,
    paddingTop: 26,
    paddingBottom: 22,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 20,
    elevation: 12,
  },
  modalCloseButton: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F1F5F3',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  modalAvatarWrap: {
    alignItems: 'center',
    marginTop: 8,
  },
  modalAvatarBorder: {
    width: 124,
    height: 124,
    borderRadius: 62,
    padding: 4,
    backgroundColor: '#DCECE0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalAvatarInner: {
    width: 116,
    height: 116,
    borderRadius: 58,
    backgroundColor: '#EAF2EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalAvatarImage: {
    width: 116,
    height: 116,
    borderRadius: 58,
  },
  modalAvatarPlaceholder: {
    fontSize: 42,
    fontWeight: '800',
    color: '#2BA14A',
  },
  modalName: {
    marginTop: 18,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '800',
    color: '#142015',
    textAlign: 'center',
  },
  modalRole: {
    marginTop: 6,
    fontSize: 16,
    lineHeight: 22,
    color: '#6B7280',
    textAlign: 'center',
  },
  modalCargo: {
    marginTop: 4,
    fontSize: 14,
    lineHeight: 20,
    color: '#2BA14A',
    textAlign: 'center',
    fontWeight: '700',
  },
  contactList: {
    marginTop: 22,
    gap: 12,
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#F6FBF7',
    borderWidth: 1,
    borderColor: '#D8EBDD',
    paddingVertical: 13,
    paddingHorizontal: 14,
  },
  contactIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#EAF6ED',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  contactTextWrap: {
    flex: 1,
  },
  contactLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: '#6B7280',
    fontWeight: '500',
  },
  contactValue: {
    marginTop: 2,
    fontSize: 14,
    lineHeight: 20,
    color: '#142015',
    fontWeight: '700',
  },
  closeAction: {
    marginTop: 20,
    borderRadius: 14,
    backgroundColor: '#2BA14A',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  closeActionText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  // Legacy profile styles are intentionally removed because this screen now renders the team credits view.
});
